### ISSUE TITLE
Test mobile styles

### ISSUE THREAD

**Issue by kimisgold** [chnm/dcdm#1]

**Comment by mebrett** [comment]
One things I've found - the map text is displaying next to the map, which is very smooshed on mobile 
![IMG_A9E1ACE42322-1](https://user-images.githubusercontent.com/2314070/78804607-5a912500-798e-11ea-9bc5-79197f0d52fd.jpeg)

**Comment by mebrett** [comment]
The text for the descriptor block on the homepage is really large, which makes the block extend beyond a single scroll - any way of making this smaller? 
![IMG_584EAF2CCA02-1](https://user-images.githubusercontent.com/2314070/78804691-75fc3000-798e-11ea-87cd-61f31e0b035d.jpeg)

**Comment by mebrett** [comment]
Also related to the map, when I try to click on a marker in mobile view, it shows up briefly and then disappears.

**Comment by kimisgold** [comment]
Map page should now have a single column layout on mobile, and I've bumped down the intro text on the homepage. I just tried replicating your marker behavior in chrome and safari on both the mobile preview on desktop and on my phone but everything seems to be working as expected. Could you provide more detail that might help me replicate what you see?

**Comment by mebrett** [comment]
Map page is working and that seems to have resolved whatever was up with the disappearing markers.

**Comment by kimisgold** [comment]
If #3 is resolved, I think we're done?
