### ISSUE TITLE
Mobile media embed not scaled

### ISSUE THREAD

**Issue by mebrett** [chnm/dcdm#2]
On media pages (from item page), larger media and longer media names are not constrained by page width.

![IMG_32E6DA44809F-1](https://user-images.githubusercontent.com/2314070/78815058-abf4e080-799d-11ea-8e70-ffe79b2b38a2.jpeg)
![IMG_0A327B7C9FF5-1](https://user-images.githubusercontent.com/2314070/78815071-b1522b00-799d-11ea-8566-2a7ab0dbcd4c.jpeg)

(as a side note, it looks like some youtube videos were imported or added as HTML media, which means they don't have a thumbnail - https://dev.dcdigitalmuseum.org/s/dc-digital-museum/item/2266 is an example, I added in the YouTube item to test media views

**Comment by kimisgold** [comment]
Media and their headings should now fit mobile widths appropriately.

With regard to the HTML vs youtube media, I think we tell Jasper about it, show him an example of how to correct it, and let them handle it on their end. They're already updating a lot of old media attachments, and I think this falls within that scope.

**Comment by mebrett** [comment]
I'll send him an email with information about how to fix that as part of their media attachment updates.
